### ISSUE TITLE
Eliminate Race conditions for signatures

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#584] opened 2018-10-16 21:35 UTC
## Description
Switch to using a db or some better locking libraries.

## Background
occurence of the race condition :- https://circleci.com/gh/ConsenSys/mythril/1110 ,
good thing is that the race condition might not be that common.

**Comment by avocadochicken** [comment] 2018-11-17 23:24
I am not sure which race condition you are refering to, but I can easily break my signature.json while running multiple mythril processes at the same time. The exception starts with this string: ""Invalid JSON in signatures file" ...

**Comment by norhh** [comment] 2018-11-18 06:11
Hi @avocadochicken ,That race condition was referring to the tests, can you mention like what version of mythril gave you that error?

**Comment by avocadochicken** [comment] 2018-11-18 10:38
Definitely v0.18.12 and maybe v0.18.11 .
I am running multiple mythril instances inside a python script (through a process pool).

```
from mythril.exceptions import CriticalError
from mythril.mythril import Mythril
from mythril.version import VERSION

...

def worker(addr, mythril_modules):
	try:
		mythril = Mythril()
		mythril.set_api_rpc('{}:{}'.format(geth[0], geth[1]))
		address, _ = mythril.load_from_address(addr)

		report = mythril.fire_lasers(
			strategy='dfs',
			max_depth=22,
			execution_timeout=30,
			address=address,
			verbose_report=True,
			modules=mythril_modules)

		return report.as_json()

	except CriticalError as ce:
		return {'error': str(ce)}

	except:
		return {'error': 'Mythril Exception'}
...
```

Here a call to mythril raises a CriticalError with the mentioned string as reason.

But: You do not need to run a process pool. Just run the same python script multiple times at the same time and the failure will also occur. The only way to get mythril running again, is to remove the files config.ini and signatures.json (inside my ~./mythril - I am on linux).

**Comment by avocadochicken** [comment] 2018-11-19 18:39
I just updated at the time of writing. I must admit, I had no single failure yet.

**Comment by avocadochicken** [comment] 2018-11-20 21:16
It broke again. Now the config.ini:
```configparser.DuplicateOptionError: While reading from '/home/user/.mythril/config.ini' [line  7]: option 'leveldb_dir' in section 'defaults' already exists```

```$ cat ~/.mythril/config.ini
[defaults]
leveldb_dir = /home/user/.ethereum/geth/chaindata
dynamic_loading = infura

Linux: ~/.ethereum/geth/chaindata
#– Windows: %USERPROFILE%\AppData\Roaming\Ethereum\geth\chaindata
leveldb_dir = /home/user/.ethereum/geth/chaindata
#– To connect to Infura use dynamic_loading: infura
#– To connect to Rpc use dynamic_loading: HOST:PORT / ganache / infura-[network_name]
#– To connect to local host use dynamic_loading: localhost
dynamic_loading = infura
```

The file is autogenerated and was deleted by myself beforehand. I was running 8 processes for approx. 40 hours before this caused the crash (v.0.19.6). And yes, this is caused by running multiple mythril processes at the same time.
In the past I was running a single process and I was running multiple processes concurrently (on multiple machines) as well. The cause is running multiple mythril processes on one machine at the same time. I am quite confident by by now that this is the reason (after scanning millions of contracts).

Please excuse me that I put this issue here.

**Comment by norhh** [comment] 2018-11-21 06:57
Oh! we didn't put any locks on the config.ini file :smile: yet, thanks for informing.

**Comment by avocadochicken** [comment] 2018-11-21 12:59
Could you link the patch here please when it is done? I want to fix it on my machines as well.

**Comment by dmuhs** [comment] 2018-11-28 08:41
This will hopefully not be an issue anymore with #758 merged. :+1:

**Closed by dmuhs** 2018-11-28 08:41 UTC
Labels: enhancement, in progress

**Comment by Danc2050** [comment] 2019-09-30 01:26
This issue still occurs when running mythril with multiple threads.

**Comment by norhh** [comment] 2019-09-30 10:25
hey @Danc2050 can you provide the exact stack trace of the issue?

**Comment by Danc2050** [comment] 2019-10-01 21:12
```
mythril.interfaces.cli [ERROR]: IPC / RPC error: 429 0mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 761, in parse_args_and_execute
    config = set_config(args)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 520, in set_config
    config = MythrilConfig()
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/mythril/mythril_config.py", line 29, in __init__
    self._init_config()
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/mythril/mythril_config.py", line 76, in _init_config
    config.read(self.config_path, "utf-8")
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
```

**Comment by Danc2050** [comment] 2019-10-01 21:15
Additionally, I am unsure if this is a related issue, but I seem to get some `CRITICAL` errors on some addresses:
```
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last): 
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 179, in __init__
    self.laser.sym_exec(world_state=world_state, target_address=address.value)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 158, in sym_exec
    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 212, in _execute_transactions
    execute_message_call(self, address)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 244, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 294, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 584, in _execute_pre_hook
    hook(global_state)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 224, in sstore_hook
    self.update_sstores(annotation.path, location)
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 118, in update_sstores
    if target_location not in self.sstores_on_path[address]:
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__ 
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/smt/bitvecfunc.py", line 114, in _comparison_helper
    a.input_ == b.input_ if inputs_equal else a.input_ != b.input_,
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__ 
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/u/danc2/.local/lib/python3.6/site-packages/mythril/laser/smt/bitvecfunc.py", line 112, in _comparison_helper
    Bool(cast(z3.BoolRef, operation(a.raw, b.raw)), annotations=union),
  File "/u/danc2/.local/lib/python3.6/site-packages/z3/z3.py", line 929, in __eq__ 
    return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
  File "/u/danc2/.local/lib/python3.6/site-packages/z3/z3core.py", line 1661, in Z3_mk_eq
    _elems.Check(a0)
  File "/u/danc2/.local/lib/python3.6/site-packages/z3/z3core.py", line 1378, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'Sorts (_ BitVec 256) and (_ BitVec 512) are incompatible'
```

**Comment by norhh** [comment] 2019-10-02 16:43
@Danc2050 the error isn't exactly related to the issue but is a new error. You can also run mythril without using CLI where you can circumvent this problem but will require some effort. Will probably do something like adding a new arg for parallelisation.
And thanks for the other bug report.

**Comment by Danc2050** [comment] 2019-10-03 23:45
A side note for anyone who wants to avoid this bug: Multiprocessing in Python seems to be side-stepping the issue while still allowing for CLI use.

**Comment by Danc2050** [comment] 2019-10-05 06:05
@norhh Hey Norhh. I am trying to find alternatives to run Mythril not in the CLI mode, but am not really finding any resource on how to do this. Do you have any suggestions?
